return {
  'nvim-treesitter/nvim-treesitter',
  event = { 'BufReadPost' },
  build = function()
    pcall(require('nvim-treesitter.install').update { with_sync = false })
  end,
  config = function()
    require('nvim-treesitter.configs').setup {
      ensure_installed = {
        'vim',
        'c',
        'regex',
        'make',
        'cmake',
        'meson',
        'ninja',
        'lua',
        'bash',
        'query',
        'json',
        'jsonc',
        'javascript',
        'jsdoc',
        'typescript',
        'tsx',
        'prisma',
        'html',
        'htmldjango',
        'css',
        'graphql',
        'python',
        'java',
        'rust',
        'toml',
        'yaml',
        'go',
        'gomod',
        'godot_resource',
        'dockerfile',
        'cpp',
        'latex',
        'markdown',
        'markdown_inline',
        'nix',
        'kotlin',
        'solidity',
        'zig',
        'vimdoc',
        'r',
      },
      highlight = {
        enable = true,
        disable = {},
      },
      incremental_selection = {
        enable = false,
      },
      indent = {
        enable = true,
        disable = {},
      },
    }
  end,
}
