# vim:ft=yaml.ansible
- name: clone neovim
  git:
    repo: https://github.com/neovim/neovim
    dest: "{{ nvim_dest }}"
    force: true
  register: nvim_git

- name: make distclean
  when: nvim_git.changed == true
  make:
    chdir: "{{ nvim_dest }}"
    target: distclean

- name: make
  when: nvim_git.changed == true
  make:
    chdir: "{{ nvim_dest }}"
    jobs: 8
    params:
      CMAKE_BUILD_TYPE: "Release"
      CMAKE_INSTALL_PREFIX: "{{ ansible_env.HOME }}/.local/"

- name: make install
  when: nvim_git.changed == true
  make:
    chdir: "{{ nvim_dest }}"
    target: install
